Business Dataset

In [1]:
import pandas as pd

business = pd.read_json(
    "/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/yelp_dataset/yelp_academic_dataset_business.json",
    lines=True
)

In [2]:
business.head(3)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
0,Pns2l4eNsfO8kk83dixA6A,"Abby Rappoport, LAC, CMQ","1616 Chapala St, Ste 2",Santa Barbara,CA,93101,34.426679,-119.711197,5.0,7,0,{'ByAppointmentOnly': 'True'},"Doctors, Traditional Chinese Medicine, Naturop...",None
1,mpf3x-BjTdTEA3yCZrAYPw,The UPS Store,87 Grasso Plaza Shopping Center,Affton,MO,63123,38.551126,-90.335695,3.0,15,1,{'BusinessAcceptsCreditCards': 'True'},"Shipping Centers, Local Services, Notaries, Ma...","{'Monday': '0:0-0:0', 'Tuesday': '8:0-18:30', ..."
2,tUFrWirKiKi_TAnsVWINQQ,Target,5255 E Broadway Blvd,Tucson,AZ,85711,32.223236,-110.880452,3.5,22,0,"{'BikeParking': 'True', 'BusinessAcceptsCredit...","Department Stores, Shopping, Fashion, Home & G...","{'Monday': '8:0-22:0', 'Tuesday': '8:0-22:0', ..."

In [3]:
business.shape

(150346, 14)

In [4]:
business.columns

Index(['business_id', 'name', 'address', 'city', 'state', 'postal_code',
       'latitude', 'longitude', 'stars', 'review_count', 'is_open',
       'attributes', 'categories', 'hours'],
      dtype='object')

In [30]:
business.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150346 entries, 0 to 150345
Data columns (total 14 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   business_id   150346 non-null  object
 1   name          150346 non-null  object
 2   address       150346 non-null  object
 3   city          150346 non-null  object
 4   state         150346 non-null  object
 5   postal_code   150346 non-null  object
 6   latitude      150346 non-null  float64
 7   longitude     150346 non-null  float64
 8   stars         150346 non-null  float64
 9   review_count  150346 non-null  int64
 10  is_open       150346 non-null  int64
 11  attributes    136602 non-null  object
 12  categories    150243 non-null  object
 13  hours         127123 non-null  object
dtypes: float64(3), int64(2), object(9)
memory usage: 16.1+ MB

In [29]:
business.describe()

,latitude,longitude,stars,review_count,is_open
count,150346.000000,150346.000000,150346.000000,150346.000000,150346.00000
mean,36.671150,-89.357339,3.596724,44.866561,0.79615
std,5.872759,14.918502,0.974421,121.120136,0.40286
min,27.555127,-120.095137,1.000000,5.000000,0.00000
25%,32.187293,-90.357810,3.000000,8.000000,1.00000
50%,38.777413,-86.121179,3.500000,15.000000,1.00000
75%,39.954036,-75.421542,4.500000,37.000000,1.00000
max,53.679197,-73.200457,5.000000,7568.000000,1.00000

In [7]:
business.isnull().sum()

business_id         0
name                0
address             0
city                0
state               0
postal_code         0
latitude            0
longitude           0
stars               0
review_count        0
is_open             0
attributes      13744
categories        103
hours           23223
dtype: int64

User Dataset

In [8]:
user = pd.read_json("/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/yelp_dataset/yelp_academic_dataset_user.json", lines = True, nrows=10000)

In [9]:
user.head(3)

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18

In [10]:
user.shape

(10000, 22)

In [11]:
user.columns

Index(['user_id', 'name', 'review_count', 'yelping_since', 'useful', 'funny',
       'cool', 'elite', 'friends', 'fans', 'average_stars', 'compliment_hot',
       'compliment_more', 'compliment_profile', 'compliment_cute',
       'compliment_list', 'compliment_note', 'compliment_plain',
       'compliment_cool', 'compliment_funny', 'compliment_writer',
       'compliment_photos'],
      dtype='object')

In [12]:
user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             10000 non-null  object
 1   name                10000 non-null  object
 2   review_count        10000 non-null  int64
 3   yelping_since       10000 non-null  object
 4   useful              10000 non-null  int64
 5   funny               10000 non-null  int64
 6   cool                10000 non-null  int64
 7   elite               10000 non-null  object
 8   friends             10000 non-null  object
 9   fans                10000 non-null  int64
 10  average_stars       10000 non-null  float64
 11  compliment_hot      10000 non-null  int64
 12  compliment_more     10000 non-null  int64
 13  compliment_profile  10000 non-null  int64
 14  compliment_cute     10000 non-null  int64
 15  compliment_list     10000 non-null  int64
 16  compliment_note     10000 non-null  int64
 17  compliment_plain    10000 non-null  int64
 18  compliment_cool     10000 non-null  int64
 19  compliment_funny    10000 non-null  int64
 20  compliment_writer   10000 non-null  int64
 21  compliment_photos   10000 non-null  int64
dtypes: float64(1), int64(16), object(5)
memory usage: 1.7+ MB

In [31]:
user.describe()

,review_count,useful,funny,cool,fans,average_stars,compliment_hot,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
count,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,278.61810,911.666300,465.440600,606.360300,32.559700,3.832046,60.317000,8.324200,6.862600,5.405000,3.415300,38.890800,95.107200,85.805900,85.805900,33.117200,23.826100
std,502.63081,3695.356472,2292.975591,3071.287502,162.946065,0.447192,337.486109,64.614323,97.454004,38.826959,39.377848,186.300067,606.325624,451.382152,451.382152,184.173485,245.570463
min,1.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,34.75000,45.750000,10.000000,14.000000,2.000000,3.590000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
50%,115.00000,176.000000,55.000000,68.000000,7.000000,3.840000,3.000000,2.000000,0.000000,0.000000,0.000000,5.000000,6.000000,6.000000,6.000000,3.000000,1.000000
75%,323.00000,628.000000,239.000000,299.000000,25.000000,4.080000,20.000000,5.000000,2.000000,2.000000,1.000000,19.000000,28.000000,33.000000,33.000000,16.000000,4.000000
max,16567.00000,173089.000000,98459.000000,144849.000000,12497.000000,5.000000,12391.000000,4347.000000,7039.000000,1744.000000,2607.000000,8616.000000,28974.000000,13280.000000,13280.000000,7309.000000,14045.000000

In [14]:
user.isnull().sum()

user_id               0
name                  0
review_count          0
yelping_since         0
useful                0
funny                 0
cool                  0
elite                 0
friends               0
fans                  0
average_stars         0
compliment_hot        0
compliment_more       0
compliment_profile    0
compliment_cute       0
compliment_list       0
compliment_note       0
compliment_plain      0
compliment_cool       0
compliment_funny      0
compliment_writer     0
compliment_photos     0
dtype: int64

Review Dataset

In [15]:
review = pd.read_json("/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/yelp_dataset/yelp_academic_dataset_review.json", lines = True, nrows = 100000)

review.head(3)

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30

In [16]:
review.shape

(100000, 9)

In [17]:
review.columns

Index(['review_id', 'user_id', 'business_id', 'stars', 'useful', 'funny',
       'cool', 'text', 'date'],
      dtype='object')

In [18]:
review.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   review_id    100000 non-null  object
 1   user_id      100000 non-null  object
 2   business_id  100000 non-null  object
 3   stars        100000 non-null  int64
 4   useful       100000 non-null  int64
 5   funny        100000 non-null  int64
 6   cool         100000 non-null  int64
 7   text         100000 non-null  object
 8   date         100000 non-null  datetime64[ns]
dtypes: datetime64[ns](1), int64(4), object(4)
memory usage: 6.9+ MB

In [19]:
review.describe()

,stars,useful,funny,cool,date
count,100000.000000,100000.000000,100000.000000,100000.000000,100000
mean,3.842910,0.898980,0.257180,0.347030,2015-05-02 14:36:08.625299968
min,1.000000,0.000000,0.000000,0.000000,2005-03-01 17:47:15
25%,3.000000,0.000000,0.000000,0.000000,2013-12-07 13:33:34.750000128
50%,4.000000,0.000000,0.000000,0.000000,2015-09-26 23:21:59.500000
75%,5.000000,1.000000,0.000000,0.000000,2017-04-08 12:26:05.249999872
max,5.000000,320.000000,98.000000,49.000000,2018-10-04 18:22:35
std,1.354729,2.205186,1.010212,1.066382,NaN

In [20]:
review.isnull().sum()

review_id      0
user_id        0
business_id    0
stars          0
useful         0
funny          0
cool           0
text           0
date           0
dtype: int64

tip dataset

In [21]:
tip = pd.read_json("/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/yelp_dataset/yelp_academic_dataset_tip.json", lines = True, nrows = 100000)

In [22]:
tip.head(3)

,user_id,business_id,text,date,compliment_count
0,AGNUgVwnZUey3gcPCJ76iw,3uLgwr0qeCNMjKenHJwPGQ,Avengers time with the ladies.,2012-05-18 02:17:21,0
1,NBN4MgHP9D3cw--SnauTkA,QoezRbYQncpRqyrLH6Iqjg,They have lots of good deserts and tasty cuban...,2013-02-05 18:35:10,0
2,-copOvldyKh1qr-vzkDEvw,MYoRNLb5chwjQe3c_k37Gg,It's open even when you think it isn't,2013-08-18 00:56:08,0

In [23]:
tip.shape

(100000, 5)

In [24]:
tip.columns

Index(['user_id', 'business_id', 'text', 'date', 'compliment_count'], dtype='object')

In [25]:
tip.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_id           100000 non-null  object
 1   business_id       100000 non-null  object
 2   text              100000 non-null  object
 3   date              100000 non-null  datetime64[ns]
 4   compliment_count  100000 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 3.8+ MB

In [26]:
tip.describe()

                                date  compliment_count
count                         100000     100000.000000
mean   2014-01-16 23:24:28.094060032          0.013710
min              2009-04-16 13:11:49          0.000000
25%              2012-04-29 01:56:45          0.000000
50%              2013-12-04 21:11:37          0.000000
75%              2015-09-10 21:16:18          0.000000
max              2018-05-05 08:19:29          5.000000
std                              NaN          0.124749

In [27]:
tip.isnull().sum()

user_id             0
business_id         0
text                0
date                0
compliment_count    0
dtype: int64

checkin dataset

In [32]:
checkin = pd.read_json("/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/yelp_dataset/yelp_academic_dataset_checkin.json", lines = True, nrows = 100000)

In [33]:
checkin.head(3)

              business_id                                               date
0  ---kPU91CF4Lq2-WlRu9Lw  2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020...
1  --0iUa4sNDFiZFrAdIWhZQ  2010-09-13 21:43:09, 2011-05-04 23:08:15, 2011...
2  --30_8IhuyMHbSOcNWd6DQ           2013-06-14 23:29:17, 2014-08-13 23:20:22

In [34]:
checkin.shape

(100000, 2)

In [35]:
checkin.columns

Index(['business_id', 'date'], dtype='object')

In [36]:
checkin.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 2 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   business_id  100000 non-null  object
 1   date         100000 non-null  object
dtypes: object(2)
memory usage: 1.5+ MB

In [37]:
checkin.describe()

,business_id,date
count,100000,100000
unique,100000,100000
top,---kPU91CF4Lq2-WlRu9Lw,"2020-03-13 21:10:56, 2020-06-02 22:18:06, 2020..."
freq,1,1

In [38]:
checkin.isnull().sum()

business_id    0
date           0
dtype: int64