In [1]:
import pandas as pd

business = pd.read_json("/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/yelp_dataset/yelp_academic_dataset_business.json", lines=True)

print(f"Rows: {business.shape[0]}")
print(f"Columns: {business.shape[1]}")

Rows: 150346
Columns: 14

In [2]:
restaurants = business[
    business["categories"].str.contains(
        "Restaurants",
        case=False,
        na=False
    )
].copy()

In [3]:
restaurants.shape

(52268, 14)

In [4]:
restaurants.head(5)

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
3,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,935 Race St,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ..."
5,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,615 S Main St,Ashland City,TN,37015,36.269593,-87.058943,2.0,6,1,"{'BusinessParking': 'None', 'BusinessAcceptsCr...","Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-22:0', '..."
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,8025 Mackenzie Rd,Affton,MO,63123,38.565165,-90.321087,3.0,19,0,"{'Caters': 'True', 'Alcohol': 'u'full_bar'', '...","Pubs, Restaurants, Italian, Bars, American (Tr...",None
9,bBDDEgkFA1Otx9Lfe7BZUQ,Sonic Drive-In,2312 Dickerson Pike,Nashville,TN,37207,36.208102,-86.768170,1.5,10,1,"{'RestaurantsAttire': ''casual'', 'Restaurants...","Ice Cream & Frozen Yogurt, Fast Food, Burgers,...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-21:0', '..."
11,eEOYSgkmpB90uNA7lDOMRA,Vietnamese Food Truck,,Tampa Bay,FL,33602,27.955269,-82.456320,4.0,10,1,"{'Alcohol': ''none'', 'OutdoorSeating': 'None'...","Vietnamese, Food, Restaurants, Food Trucks","{'Monday': '11:0-14:0', 'Tuesday': '11:0-14:0'..."

In [5]:
columns = ["business_id", "name", "city", "state", "postal_code", "latitude", "longitude", "stars", "review_count", "categories", "attributes", "hours", "is_open"]

restaurants = restaurants[columns]

In [8]:
restaurants.isnull().sum()

business_id        0
name               0
city               0
state              0
postal_code        0
latitude           0
longitude          0
stars              0
review_count       0
categories         0
attributes       565
hours           7278
is_open            0
dtype: int64

In [10]:
restaurants[restaurants["attributes"].isnull()].head(5)

,business_id,name,city,state,postal_code,latitude,longitude,stars,review_count,categories,attributes,hours,is_open
301,e8pMCk4bE0U4qk7z59Lxkg,Federal Donuts,Philadelphia,PA,19130,39.963042,-75.174186,4.5,11,"Sandwiches, Chicken Wings, Restaurants, Donuts...",None,"{'Monday': '8:0-15:0', 'Tuesday': '8:0-15:0', ...",1
720,GInRkBWvuyJCjFVHYdzkPQ,Licata's Italian Deli,Pottstown,PA,19464,40.242716,-75.618081,4.5,8,"Italian, Delis, Restaurants, Salad",None,"{'Tuesday': '11:0-20:30', 'Wednesday': '11:0-2...",0
964,vuL3QCjFZ7lU5LMdUAmZ9Q,Subway,Wayne,PA,19087,40.044263,-75.399354,1.5,5,"Sandwiches, Fast Food, Restaurants",None,None,0
1109,UAi8nZY-tCA758y4_8Meuw,Fullylove’s Restaurant,Tucson,AZ,85719,32.255573,-110.943539,4.5,25,"Vegan, American (New), Restaurants",None,"{'Wednesday': '17:0-22:0', 'Thursday': '17:0-2...",0
1811,Q28TlneXws1shf8ymTdxtg,Funland Raspados And Munchies,Tucson,AZ,85745,32.251145,-111.012350,4.5,6,"Restaurants, Shaved Ice, Burgers, Juice Bars &...",None,"{'Monday': '10:0-22:0', 'Tuesday': '10:0-22:0'...",1

In [11]:
restaurants[restaurants["hours"].isnull()].head(5)

,business_id,name,city,state,postal_code,latitude,longitude,stars,review_count,categories,attributes,hours,is_open
8,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,Affton,MO,63123,38.565165,-90.321087,3.0,19,"Pubs, Restaurants, Italian, Bars, American (Tr...","{'Caters': 'True', 'Alcohol': 'u'full_bar'', '...",None,0
24,4iRzR7OaS-QaSXuvYxEGKA,Super Dog,Nashville,TN,37115,36.248570,-86.719986,4.0,6,"Hot Dogs, Restaurants","{'RestaurantsReservations': 'False', 'Restaura...",None,0
36,2xVsWBNFwZOxIOdd9Mwnww,Cheeseburger In Paradise,Exton,PA,19341,40.029962,-75.630607,2.5,20,"Restaurants, Burgers","{'NoiseLevel': 'u'average'', 'HasTV': 'True', ...",None,0
62,L_TT0BFmFwORAMaA83K54A,Village Tap Room,Indianapolis,IN,46220,39.869911,-86.143577,2.5,23,"Gastropubs, Cocktail Bars, Beer Bar, Bars, Res...","{'Alcohol': 'u'none'', 'BestNights': '{'monday...",None,0
64,qfWJmJ0g96eM_fWma3ja0g,Doc Magrogan's Oyster House - West Chester,West Chester,PA,19380,39.961542,-75.603604,3.0,114,"Seafood, Restaurants, Bars, Nightlife, Cocktai...","{'WiFi': 'u'no'', 'RestaurantsAttire': 'u'casu...",None,0

In [12]:
restaurants[restaurants["attributes"].isnull()][["name","categories","is_open","stars"]]

,name,categories,is_open,stars
301,Federal Donuts,"Sandwiches, Chicken Wings, Restaurants, Donuts...",1,4.5
720,Licata's Italian Deli,"Italian, Delis, Restaurants, Salad",0,4.5
964,Subway,"Sandwiches, Fast Food, Restaurants",0,1.5
1109,Fullylove’s Restaurant,"Vegan, American (New), Restaurants",0,4.5
1811,Funland Raspados And Munchies,"Restaurants, Shaved Ice, Burgers, Juice Bars &...",1,4.5
...,...,...,...,...
149076,Pizza Hut,"Restaurants, Chicken Wings, Pizza, Food Delive...",0,1.5
149253,Sushison Tucson,"Sushi Bars, Mexican, Restaurants",1,4.0
149893,Can Tho City,"Vietnamese, Restaurants, Breakfast & Brunch, S...",1,4.0
149991,The Living Room,"Asian Fusion, Restaurants",0,4.0
150088,Margarita House- LaVergne,"Mexican, Restaurants",1,2.5

Missing Value Handling

In [13]:
restaurants = restaurants.fillna({"attributes": "Uknown", "hours": "Uknown"})

In [14]:
restaurants.isnull().sum()

business_id     0
name            0
city            0
state           0
postal_code     0
latitude        0
longitude       0
stars           0
review_count    0
categories      0
attributes      0
hours           0
is_open         0
dtype: int64

In [16]:
restaurants["business_id"].duplicated().sum()

np.int64(0)

In [17]:
restaurants.info()

<class 'pandas.core.frame.DataFrame'>
Index: 52268 entries, 3 to 150340
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   business_id   52268 non-null  object
 1   name          52268 non-null  object
 2   city          52268 non-null  object
 3   state         52268 non-null  object
 4   postal_code   52268 non-null  object
 5   latitude      52268 non-null  float64
 6   longitude     52268 non-null  float64
 7   stars         52268 non-null  float64
 8   review_count  52268 non-null  int64
 9   categories    52268 non-null  object
 10  attributes    52268 non-null  object
 11  hours         52268 non-null  object
 12  is_open       52268 non-null  int64
dtypes: float64(3), int64(2), object(8)
memory usage: 5.6+ MB

Convert file to csv and parquet

In [19]:
restaurants.to_csv(
    "/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/data/processed/restaurants_clean.csv",
    index=False
)