# Feature Engineering

## Objective

Transform the cleaned restaurant dataset into structured features that can be used by the recommendation engine.

Outputs:

- Cuisine
- Restaurant Type
- Experience
- Expanded Attributes

In [1]:
import pandas as pd

restaurants = pd.read_csv("/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/data/processed/restaurants_clean.csv")

taxonomy = pd.read_csv("/Users/edgardomosesezekielaverilla/Restaurant-Recommendation-System-Redux/data/reference/category_mapping.csv", encoding="cp1252")

In [3]:
restaurants.head(3)

,business_id,name,city,state,postal_code,latitude,longitude,stars,review_count,categories,attributes,hours,is_open
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,19107,39.955505,-75.155564,4.0,80,"Restaurants, Food, Bubble Tea, Coffee & Tea, B...","{'RestaurantsDelivery': 'False', 'OutdoorSeati...","{'Monday': '7:0-20:0', 'Tuesday': '7:0-20:0', ...",1
1,CF33F8-E6oudUQ46HnavjQ,Sonic Drive-In,Ashland City,TN,37015,36.269593,-87.058943,2.0,6,"Burgers, Fast Food, Sandwiches, Food, Ice Crea...","{'BusinessParking': 'None', 'BusinessAcceptsCr...","{'Monday': '0:0-0:0', 'Tuesday': '6:0-22:0', '...",1
2,k0hlBqXX-Bt0vf1op7Jr1w,Tsevi's Pub And Grill,Affton,MO,63123,38.565165,-90.321087,3.0,19,"Pubs, Restaurants, Italian, Bars, American (Tr...","{'Caters': 'True', 'Alcohol': ""u'full_bar'"", '...",Uknown,0

In [4]:
taxonomy.head(3)

      Category  Count Feature Type Standardized Value Keep  Notes
0  Restaurants  52268      Generic                NaN   No    NaN
1         Food  15472      Generic                NaN   No    NaN
2    Nightlife   8723   Experience                NaN  Yes    NaN

In [5]:
taxonomy_keep = taxonomy[taxonomy["Keep"] == "Yes"]

In [8]:
mapping = taxonomy_keep.set_index("Category").to_dict("index")

Test

In [9]:
restaurants.iloc[0]["categories"]

'Restaurants, Food, Bubble Tea, Coffee & Tea, Bakeries'

In [10]:
categories = [
    c.strip()
    for c in restaurants.iloc[0]["categories"].split(",")
]

In [11]:
for c in categories:
    if c in mapping:
        print(c, "->", mapping[c])

Bubble Tea -> {'Count': 277, 'Feature Type': 'Restaurant Type', 'Standardized Value': 'Bubble Tea', 'Keep': 'Yes', 'Notes': nan}
Coffee & Tea -> {'Count': 4053, 'Feature Type': 'Restaurant Type', 'Standardized Value': 'CafŽ', 'Keep': 'Yes', 'Notes': nan}
Bakeries -> {'Count': 1889, 'Feature Type': 'Restaurant Type', 'Standardized Value': 'Bakery', 'Keep': 'Yes', 'Notes': nan}